package cse15;
import java.util.Scanner;
public class Anotherformoftrycatchexample
{
	public static void main(String args[])
	{
		Scanner sc=new Scanner(System.in);
		try
		{
			int n=Integer.parseInt(sc.next());
			System.out.println(n/0);
		}
		catch(ArithmeticException | NumberFormatException e)
		{
			System.out.println("Exception caught:"+e);
		}
	}

}
